version: '3'

services:
  mySQL_DB_for_jpa_advanced:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: db_root_password
      MYSQL_DATABASE: jpa_practice_db
      MYSQL_USER: db_user_name
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    volumes:
      - mySQL_DB_for_jpa_advanced_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3300:80"
    environment:
      PMA_HOST: mySQL_DB_for_jpa_advanced
      PMA_PORT: 3306
    networks:
      - my_network

volumes:
  mySQL_DB_for_jpa_advanced_data:

networks:
  my_network:
